version: "3.9"

services:
  api:
    build:
      context: ./backend/api
    container_name: api
    environment:
      DEBUG: "0"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build:
      context: ./backend/worker
    container_name: worker
    environment:
      DEBUG: "0"
    command: ["python", "my_main.py"]
