version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config

  api:
    build:
      context: ./backend/api
    container_name: api
    depends_on:
      - postgres
      - mosquitto
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydb
      MQTT_BROKER_HOST: mosquitto
      SECRET_KEY: VERY_SECRET_KEY
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 90000 
      MQTT_BROKER_PORT: 1883
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api:/app

  worker:
    build:
      context: ./backend/worker
    container_name: worker
    depends_on:
      - postgres
      - mosquitto
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydb
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
    volumes:
      - ./backend/worker:/app

volumes:
  pgdata:
